### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ajcksyxd** [ajcksyxd/protospace-31796#1]
https://github.com/ajcksyxd/protospace-31796
https://protospace-31796.herokuapp.com/

**Comment by Yoshiyuki-Hayashi-div** [comment]
内野さん、ご提出ありがとうございます！

挙動確認させていただいたところ、全く問題ありませんでしたので、LGTMとさせていただきます🎉

実装お疲れ様でした。おめでとうございます！
